name: Revisi贸n Sintaxis README

on:
  pull_request:
    branches:
      - develop

jobs:
  check-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Revisi贸n del c贸digo
      uses: actions/checkout@v3
    
    - name: Instalando markdownlint-cli
      run: npm install -g markdownlint-cli

    - name: Revisi贸n sintaxis archivo README.md
      run: markdownlint README.md
